### ISSUE TITLE
Render glossary as a typst term list

### ISSUE THREAD

**Issue by dyc3** [dyc3/senior-design#208]
Refactor how the glossary is rendered so it uses the typst native `terms()`: https://typst.app/docs/reference/model/terms/

**Comment by Victor-M-Giraldo** [comment]
Just a quick question.

```
for (word, info) in data {
    [/ #word: #info.definition\ → #if "link" in info {link(info.link)}]
  }
```
Does this not already render the glossary as term? Or would you instead like me to use the terms constructor?

**Comment by dyc3** [comment]
According to [the examples in these docs](https://typst.app/docs/reference/model/terms/), it looks like it already does. If you can verify that it does in fact render out a `terms()` and not just a bunch of `terms.item()`, we can go ahead and close this.

**Comment by dyc3** [comment]
I'm pretty sure you can use [repr()](https://typst.app/docs/reference/foundations/repr/) to check

**Comment by Victor-M-Giraldo** [comment]
> I'm pretty sure you can use [repr()](https://typst.app/docs/reference/foundations/repr/) to check

They are being rendered as a bunch of ```terms.items()```. 

I was thinking of doing something like this ```terms(..data.map(((word, info)) => terms.item(word, [#info.definition: ...])))``` to ensure it returns a ```terms()``` but you can't use ```.map()``` on dictionaries. Any ideas on where to go from here
