### ISSUE TITLE
Ansary: Answer Judges' Questions

### ISSUE THREAD

**Issue by cjrkoa** [dyc3/senior-design#371]

**Comment by dyc3** [comment]
We got questions from the judges? Or are we trying to anticipate them?

**Comment by cjrkoa** [comment]
We're gonna get questions from judges from 4/10 - 4/13 at 11:59pm and we have 4/14 - 4/15 at 11:59pm to answer them

**Comment by Victor-M-Giraldo** [comment]
We should ask the professor if questions not asked in the Slack channel might be asked during the actual thing. I would assume not, but best to clarify.

**Comment by cjrkoa** [comment]
Sent answers to judges on Monday afternoon
